!
!  commandline.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  3/22/2012 11:58:10 AM
!
subroutine pe_setdevice()
use cudafor
implicit none

 character(len=32)::arg

 integer :: i, c1, istat, idevice=0
 
 

 c1 = command_argument_count()
 if (c1 == 1) then
   call get_command_argument(1,arg)
   idevice = ichar(arg(1:1))-48
   !print *,arg(1:1),idevice
   istat = cudasetdevice(idevice)
   if (istat .ne. 0) then
     print *,'Device setup error',cudaGetErrorString(cudaGetLastError())
	 stop
   else
     !print *,'Use cuda device #',idevice
   end if
 end if 

 !stop

end subroutine