!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  3/19/2012 11:37:45 PM
!
subroutine envtest(envr,envi, envr2, envi2)
implicit none
REAL*4 envr(32768)
REAL*4 envi(32768),envr2(32768),envi2(32768)
integer n

print *,'---- env test ----'

n = 10   
print *,'n=',n
print *,envr(n), envi(n),envr2(n),envi2(n)

n = 32768/2-1 
do n=10,32768,10000 
print *,envr(n), envi(n),envr2(n),envi2(n),n
end do
return
n = 32768/2+10 
 
print *,'n=',n,envr(n), envi(n),envr2(n),envi2(n)

n = 32768-18+1   
 
print *,'n=',n,envr(n), envi(n),envr2(n),envi2(n)

n = 32768    

print *,'n=',n,envr(n), envi(n),envr2(n),envi2(n)

end subroutine