!
!  notes.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  3/24/2012 7:47:46 PM
!
!

!input
real::sigsmax, rng, dr,rss1,rss2,rb1,rb2,rbp1,rbp2,rdb1,&
  rdb2,rdbp1,rdbp2, bdint, bssint,bgint, blint,bdenint,&

real,dimension(rng_steps) ::etas, detas, d2etas
real:: bd(251),bss(251),bg(251),bden(251),bl(251),&
  bsws(251),bswl(251),dbd(251)
integer:: rng_steps = int(rngmax/dr),ib, ibp,


!local
real::rsint, rsdotint, rsdot2int,fss,fb,fbp,fdb,fdbp,bdint,&
  bssint,bgint,blint,bdenint,bsint,bswlint,dbdint,dbssint
integer::irtmp,

integer::i,ix_cuda, 

!output
real:: ss1(nz2),ss2(nz2)
